### ISSUE TITLE
Bug - After HA update - Message malformed automation error

### ISSUE THREAD

**Issue by matfil92** [jumping2000/ha-packages#9]
### Package name

CN FSM Elettrodomestici 2023.9.0

### Home Assistant Core Version

2024.8.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Dopo l'aggiornamento ad HA OS e Core ho questo errore nelle impostazioni di sistema

```
Automation MF - Asciugatrice failed to set up
The blueprinted automation "MF - Asciugatrice" (automation.mf_asciugatrice) failed to set up.

Error:Unknown device '8f06c81665e351a24803d0ceec3db523'.
```

E se apro l'automazione per verificare i device, li ha mantenuti tutti gli esistenti ed inoltre il device 8f06c81665e351a24803d0ceec3db523 non esiste.
Se provo a fare click su salva ottengo questo errore:
`Message malformed: string value is None for dictionary value @ data['action'][0]['choose'][4]['sequence'][0]['choose'][0]['sequence'][1]['default'][0]['then'][0]['device_id']`

Premetto che prima dell'aggiornamento le tre automazioni Lavatrice, Asciugatrice e Lavastoviglie funzionavano a dovere

Suggerimenti?

### Automation YAML config

```yaml
alias: MF - Asciugatrice
description: ""
use_blueprint:
  path: jumping2000/cn_fsm_appliances.yaml
  input:
    power_plug: sensor.bagp_p_dx_power
    energy_plug: sensor.bagp_p_dx_energy
    status: input_select.dryer_status
    status_sensor: sensor.dryer_status
    counter_sensor: counter.cicli_asciugatrice
    helper_runtime: input_boolean.asciugatrice_runtime
    helper_total_energy: input_number.asciugatrice_energia_iniziale
    helper_maintenance_alert: input_number.lavastoviglie_avviso_manutenzione
    appliance: Asciugatrice
    media_player_alexa:
      - media_player.alexa_cucina
      - media_player.echo_matteo
      - media_player.echo_pop_di_matteo
      - media_player.echo_dot_di_matteo
      - media_player.sistema_audio
    use_centro_notifiche: true
    delay_middle: 6
    power_end: 5
    media_player_google:
      - null
```

### To Reproduce

1. Go to 'settings'
2. Click on 'Automation'
3. Trigger the automation 

### Expected behavior

Funzionamento senza problemi

### Actual Behaviour

Le 3 automazioni sono rosse e completamente disattivate dal sistema

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
